### ISSUE TITLE
Ubuntu Error: Could not find pid file for ConnectorDB backend

### ISSUE THREAD

**Issue by KastanDay** [heedy/heedy#332]
Hello ConnectorDB folks!

I loved using this program on my Windows laptop, so I wanted to install it on my Ubuntu linux box at home, but have not been able to get past this bug. 

I thought it was worth posting here because of the error: "Error: Could not find pid file for ConnectorDB backend. Looks like the servers are off already." I wasn't sure which server that was referring to. Is it my own? But how could it be offline, I'm only setting it up in this very moment. 

Below is the full dialogue. I'd really appreciate any help you could offer in getting it set up! 
Thank you so much!
-Kastan

```
$ python3 datamanager.py
2019-01-29 23:10:45,609 Local ConnectorDB found: 0.3.0-git.1146
2019-01-29 23:10:45,649 Creating new cache file...

ConnectorDB Logging is not set up. Please choose:

    1) Log into existing ConnectorDB server
    2) Create a locally managed ConnectorDB instance
    3) Import a ConnectorDB instance from folder
    q) Quit

Choice [DEFAULT: 2]: 2
ConnectorDB Username: Kastan
Password:
Repeat Password:
Device Name [DEFAULT: laptop]: BetaServer
2019-01-29 23:11:06,208 Creating new ConnectorDB database at /home/memento/.local/share/connectordb/cdb
INFO[0000] Creating new ConnectorDB database at '/home/memento/.local/share/connectordb/cdb'
INFO[0000] Setting up redis server
INFO[0000] Setting up gnatsd server
INFO[0000] Setting up sqlite3 database
INFO[0000] Creating user Kastan (root@localhost)
2019-01-29 23:11:06,549 Starting database at /home/memento/.local/share/connectordb/cdb
INFO[0000] Starting ConnectorDB
INFO[0000] Staring redis on port 6380
panic: Could not find executable redis-server

goroutine 1 [running]:
dbsetup.GetExecutablePath(0xcc7c5d, 0xc, 0xcc060e, 0x5)
        /home/daniel/Desktop/ConnectorDB/connectordb/src/dbsetup/filetools.go:195 +0x1a8
dbsetup.(*RedisService).Start(0xc42036c060, 0x0, 0x0)
        /home/daniel/Desktop/ConnectorDB/connectordb/src/dbsetup/redis.go:54 +0xdc
dbsetup.Start(0xc4202a0780, 0xc4202a0780, 0x0)
        /home/daniel/Desktop/ConnectorDB/connectordb/src/dbsetup/allservices.go:140 +0xa17
commands.glob..func8(0x1280180, 0xc4203522c0, 0x1, 0x1, 0x0, 0x0)
        /home/daniel/Desktop/ConnectorDB/connectordb/src/commands/start.go:85 +0x34e
github.com/spf13/cobra.(*Command).execute(0x1280180, 0xc420352270, 0x1, 0x1, 0x1280180, 0xc420352270)
        /home/daniel/go/src/github.com/spf13/cobra/command.go:644 +0x3f2
github.com/spf13/cobra.(*Command).ExecuteC(0x127fb20, 0x0, 0x1, 0x1)
        /home/daniel/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0x127fb20, 0xc420213f68, 0x0)
        /home/daniel/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
        /home/daniel/Desktop/ConnectorDB/connectordb/src/main.go:12 +0x31
2019-01-29 23:11:06,590 Logging in as Kastan to http://localhost:3124
2019-01-29 23:11:06,599 Starting new HTTP connection (1): localhost
2019-01-29 23:11:06,600 Stopping database at /home/memento/.local/share/connectordb/cdb
INFO[0000] Stopping ConnectorDB
Error: Could not find pid file for ConnectorDB backend. Looks like the servers are off already.
Usage:
  connectordb stop [config file path or database directory] [flags]

Global Flags:
      --cpuprofile string   File to which a cpu profile of ConnectorDB will be written
      --logfile string      The file to which log output is written
  -l, --loglevel string     The types of messages to show (debug,info,warn,error)

ERRO[0000] Could not find pid file for ConnectorDB backend. Looks like the servers are off already.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f0b5898aac8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3124): Max retries exceeded with url: /api/v1/crud/Kastan/user (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0b5898aac8>: Failed to establish a new connection:[Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "datamanager.py", line 426, in <module>
    dm = DataManager(args.folder, createCallback)
  File "datamanager.py", line 72, in __init__
    createCallback(self)
  File "datamanager.py", line 421, in createCallback
    dm.create(username, password, device, True)
  File "datamanager.py", line 316, in create
    isprivate, deviceOverwriteCallback)
  File "datamanager.py", line 278, in login
    cdb = connectordb.ConnectorDB(username, password, serverurl)
  File "/usr/local/lib/python3.5/dist-packages/connectordb/_connectordb.py", line 42, in __init__
    if self.apikey is not None:
  File "/usr/local/lib/python3.5/dist-packages/connectordb/_device.py", line 118, in apikey
    if "apikey" in self.data:
  File "/usr/local/lib/python3.5/dist-packages/connectordb/_connectorobject.py", line 24, in data
    self.refresh()
  File "/usr/local/lib/python3.5/dist-packages/connectordb/_connectorobject.py", line 18, in refresh
    self.metadata = self.db.read(self.path).json()
  File "/usr/local/lib/python3.5/dist-packages/connectordb/_connection.py", line 141, in read
    params=params))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 492, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3124): Max retries exceeded with url: /api/v1/crud/Kastan/user (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0b5898aac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by dkumor** [comment]
It looks like you don't have one or more dependencies installed. In particular, the error message you posted above complains about redis not being installed.

Try the following:
1) Install redis: `sudo apt-get install redis-server`
2) Disable redis on startup:
```
sudo systemctl disable redis-server.service
sudo systemctl stop redis-server.service
```
3) `rm -rf /home/memento/.local/share/connectordb` to delete the failed setup
4) Try again

Hopefully with redis installed, it will work properly (On windows CDB comes with redis automatically).

**Comment by dkumor** [comment]
One thing to note is that on the newest version of Ubuntu, (with gnome 3), there might be issues with the icon showing up - this is because gnome removed the icon tray, without putting anything in its place. If it doesn't show up, you might have to install a gnome extension to bring the icons back!

**Comment by KastanDay** [comment]
Very interesting, I suspected that was the case given what I know about `pyhook`. But I'm afraid I don't have the familiarity with the connectordb code base to execute on those ideas myself. I'm also fairly rusty on Python so I'm reluctant to get my hands dirty at the moment. My time-efficent solution currently is to settle for using connectorDB + [Logkeys](https://github.com/kernc/logkeys) in parallel, even if that's sub-optimal. 
Or, I'd be thrilled if you'd like to help more with that extension. I can help where possible, but I'm not sure I'd be of much use. If it's not hard, could be worth it and others might enjoy that utility too!

**Comment by dkumor** [comment]
I totally understand - I am super busy these days too. If you open an issue for this in the connectordb-desktop repository, then I might try finding the old keylogger code one of these weekends, and adding it as an optional logger.
